theme: jekyll-theme-minimal
title: BCRP Links
description: Formerly mohsinali.ca but still in perennial development...

#Blog Posts
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Podcast" # The post list page content
