theme: jekyll-theme-minimal
title: BCRP Links
description: Formerly mohsinali.ca but still in perennial development...

#Blog Posts
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
