theme: jekyll-theme-minimal
title: BCRP Links
description: Formerly <mohsinali.ca> but still in perennial development...

#Blog Posts
plugins:
- jekyll-paginate

paginate: 2
paginate_path: "/blog/page:num/"

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Podcast" # The post list page content
    
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
