# Newborn Nursery

## Rotation Specific Entities
**BMC** Black binder and printouts on walls in work room include all clinical practice guidelines/approaches
**BWH** All clinical practice guidelines are available online via BWH PikeNotes

## Gestational Age
**Early Preterm** * <34 0/7

**Late Preterm** ** 34 0/7 - 36 6/7

**Early Term** 37 0/7 - 38 6/7

**Full Term** 39 0/7 - 40 6/7

**Late Term** 41 0/7 - 41 6/7

**Postterm** 42 0/7+

*Use Fenton growth chart for late preterm. If between 37 0/7 and 37 6/7, chart on Fenton, Olsen and WHO and take better number

**“Great pretenders”** - risk of resp distress, apnea, temp dysregulation, poor feeding

## Normal Infant Feeding
- All babies typically lose up to 2-3% of BW/day, should not lose more than 10-12% of BW before discharge. Babies born by c-section may lose more weight than vaginal births (Mom and therefore baby get IV fluids during delivery). Usually start gaining on DOL4.  Baby should regain BW by 10-14 days and should gain 20-30g/day for first month, or 5 oz per week (“an ounce a day and time off for weekends”).
- Babies usually awake for first 5-6 hrs and then sleepy for 24 hrs. Start waking up on DOL2 and are hungry (“all day cafe”).  Sometimes if baby is not getting enough with feeds, may shut down and appear sleepy.

### Breastfeeding
Newborns who are **breastfed need to eat every 2-3 hours**, on demand.  If showing hunger cues, feed, even if just fed. No such thing as newborn “using mother as a pacifier.” Cluster feeding (at breast for several hours) happens on Day 2-3, as baby tries to get milk to come in. Mother may feel tired and frustrated. Reassure that this is NORMAL. Milk usually comes in around 3-5 days.

#### Breastfeeding Tips
-Respond to **infant feeding cues** (early → late: stirring, turning head, mouth opening, hand in mouth, stretching, crying). 



- **Infant latch**: Line up baby nose to nipple.  Stroke baby lips with nipple.  Aim nipple to roof of baby’s mouth.  Support baby’s neck at the shoulders so head tips back and **bring baby onto breast (*not* breast to baby).**
>> - Signs of a good latch: lips flanged outward, **most of areola hidden** in mouth, nose free
- Breast milk can sit out 8 hrs if freshly pumped, or 5 days in refrigerator. Can store 6-12 mos in freezer. Don’t refreeze thawed breastmilk.
- Mothers can hand express and/or pump to stimulate milk production.  Holding baby skin to skin also stimulates because of hormone release. Hand expression is helpful especially for colostrum or if engorged. Can feed to baby via spoon or syringe. 
- For determining if mom’s meds are safe during breastfeeding: **LactMed** (part of NIH ToxNet), **Hale’s Medications & Mother’s Milk** (physical book in BMC workroom or HalesMeds.com.  Physical book in BWH nursery)

#### Contraindications to breastfeeding
Absolute: infant w/ galactosemia, mom w/ **HIV** or HTLV-1/2, mom actively using **illicit drugs, including marijuana or EtOH** (exception: moms in methadone program, see “NAS”), HSV lesion on breast.  OK to feed expressed milk: mom w/ varicella or active TB. HCV positive mom ok to breastfeed unless nipples cracked or bleeding.

### Formula Feeding
- Formula fed babies eat **every 3-4 hours** (if sleeps > 4 hours, wake baby up). Infant stomach is size of a blueberry on DOL1 → lime at DOL7. Volume increases gradually over first several days. DOL1: 10-15 mL per feed, DOL2: 15-30 mL/feed; DOL3: 30-45 mL/feed, DOL4: 45-60 mL/feed. Give baby what last took and if not settled, feed more. Follow baby’s cues.

- Formula, in 60 mL bottles as supplied by hospital, needs to be consumed within 1 hour of starting feed and then discarded.

### Tongue Ties





Type
Exam
Image
Mgmt
Normal

Tongue appears flat and broad
Tongue extends over bottom teeth
Can swipe finger under tongue uninterrupted
N/A
N/A
Type 4: Mild
Posterior tie on tongue, may be submucosal
N/A
Generally nothing
Type 3: Moderate
Tie is proximal to 50% of length of tongue

Consider lactation consult
Type 2: Severe

Tie is distal to 50% of length of tongue
May create a hump or cupping


Frenulectomy if interfering with feeding
Type 1: Complete
Tie extends to tip of tongue

Likely frenulectomy

## Newborn Behavior
**Infant states**: newborn behavior related to state. There are 6 states, all normal. Infant’s ability to self-regulate is related to ability to move fluidly from one state to next, affected by gestational age and perinatal stress.

Deep sleep -> light sleep -> drowsy -> active alert -> fussy -> full cry

## Anticipatory Guidance / Discharge Teaching

### Feeding
**feed on demand**, only breastmilk or formula, **8-12x in 24h - “8 or more in 24.”** Wake up baby after 3-4h to feed.

### Normal Voiding / Stooling
Should have **as many wet diapers as days of life**, up to 6-8 after 1 week of life.  Should have **at least 2-3 stools/day.** Color may change, should be yellow, seedy.. Bloody or white stools would be concerning.

### Cord Care
Keep **cord clean (sponge bath), dry, and uncovered by diaper**. Will fall off on its own in about 10 days.

### Circumcision Care
Leave dressing on for 24h. Use petroleum jelly on penis with every diaper change.  Written for tylenol x 2 doses in hospital but most babies do not need it and do fine with being skin to skin for comfort.

### Safe Sleep
Baby should sleep on back in own crib with tight fitted sheet.  NO loose blankets, stuffed animals, positioning aids.  No propping on side. Swaddling is good.  Tuck swaddle blanket under baby, or use velcro swaddler.

### Tummy Time
Give baby time on tummy.  As newborn, can lie on parents chest.  Person holding baby should put baby down if feeling sleepy.  Don’t sleep with baby.

### Consoling
Babies cry to communicate. Never shake the baby. Can put baby in crib or pass baby to other caretaker if frustrated. Giving baby hand to suck on and swaddling help with consoling.

### Illness
- Visitors should wash hands before handling baby.  Avoid crowds, passing baby among visitors, and people with colds, especially for first few months.  Tell older sibs to touch baby’s feet, not hands and face (newborns can’t yet put their feet in mouths).
- **Infant fever (taken rectally) is > 100.4 F:**  Seek medical attention if baby seems “off”: eating less than usual, making fewer wet diapers, fussy or lethargic.

## Hyperbilirubinemia

### Definition
Infants ≥ 35 wks GA: TB > 95th percentile (2004 AAP Guidelines/Bhutani nomograms)

### Pathophysiology
↑ RBC turnover, ↓ clearance (UGT1A1 activity), ↑ enterohepatic recirculation. **Within first 24 hours of life = ALWAYS pathologic.**

| **Indirect**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | **Direct - ALWAYS pathologic**                                                                                                                                                |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| - **Breastfeeding jaundice**: first week of life due to insufficient feeding and dehydration - **Breast *milk* jaundice**: persistent after first week of life, unknown mechanism, ?substance in milk  blocks bilirubin breakdown - **ABO or Rh incompatibility**: suspect if set-up, previous child with hemolytic disease of the newborn,   fetal hydrops, jaundice in the first 24 hours of life - Red cell membrane defects (spherocytosis and elliptocytosis) - G6PD deficiency - Sepsis - Decreased clearance – Crigler-Najjar syndrome, Gilbert syndrome - Intestinal obstruction | - **Anatomic** (intestinal obstruction, cysts, tumors,  biliary atresia) - **Infection/sepsis** - Metabolic - Gestational alloimmune liver disease (neonatal hemochromatosis) |

### Evaluation

**Healthy infants**: Obtain routine transcutaneous bili (TcB) at DOL2 and plot on [bilitool.org](http://bilitool.org/). If ABO/Coombs set-up, check TcB at 12HOL and 24HOL.

- Determine **follow-up frequency** based on **risk for developing severe hyperbili** (use risk zone, which is generated by nomogram + GA + presence of hyperbili risk factors [jaundice in first 24 hours, ABO incompatibility/positive direct Coombs, GA 35-36w, sibling required phototherapy, cephalohematoma, exclusive breastfeeding, East Asian race])

- Determine **phototherapy threshold** based on **neurotoxicity risk** (use GA AND presence of neurotoxicity risk factors [isoimmune hemolytic disease, G6PD, asphyxia, lethargy, temp instability, sepsis/acidosis, albumin less than 3.0)
  - If above phototherapy threshold, check total serum bili (TSB). Once TSB is used, TcB may not be used again.

- Consider checking CBC, retic, hemolysis labs (LDH, haptoglobin, smear), G6PD activity.

### Management
Reconsider early discharge (before 72 HOL) if bili high intermediate risk.  Phototherapy as per BiliTool curves. If near exchange levels: aggressive phototherapy, aggressive hydration (IV+PO). IVIG for isoimmune hemolytic disease. Call blood bank before exchange transfusion

## Infant of a Diabetic Mother (IDM)

### Increased risks
**LGA** (BW ≥ 4000g or ≥ 90th percentile for GA) → birth injury (shoulder dystocia, clavicular fracture), preterm birth, **RDS/TTN, hypoglycemia** (maternal hyperglycemia → infant hyperinsulinism → hypoglycemia; resolves in 2-4d), hypertrophic cardiomyopathy (of interventricular septum), **hyperbili, polycythemia** (Hct > 65% → hyperviscosity → exchange transfusion if symptomatic)

### Congenital anomalies
**Transposition of great arteries**, double outlet RV, VSD, truncus arteriosus, hypoplastic L heart syndrome, **small L colon syndrome** → functional lower bowel obstruction (contrast enema is diagnostic and curative)

### Management
Obtain glucose at 2-4HOL, then pre-feed until glucoses stabilize.  Consider checking Hct in first hours of life. Check Ca++/Mg if jittery or seizure

### Hypoglycemia

| **Glucose (mg/dl) | **<25**                                                                       | **25-39**                                                                                                                               | **>=40**                                                                       |
|-------------------|-------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| **Mgmt**          | **Admit to NICU** and give 2 cc/kg  bolus of D10W followed by infusion of D10 | - Feed 10-15 mL colostrum / formula and re-check - **May give glucose gel 2x (with feed) in  first 24 HOL before transferring to NICU** | - Check 3 **pre-feed POC glucoses <= 3 hours apart;**  if normal, routine care |

- Risk Factors: IDM, LGA, SGA, late preterm or post-term, <2500g, discordant twin, maternal medications (e.g., propranolol)
- After 48 HOL, glucose levels should be >60
- If hypoglycemia persists, send critical labs. Consider diazoxide if hyperinsulinism.

## Neonatal Abstinence Syndrome (NAS)

### Pathophysiology
Behavioral dysregulation seen 2/2 drug withdrawal in infants chronically exposed in utero to opiods (methadone, buprenorphine, morphine, oxycodone, hydromorphone, heroin) and other substances (nicotines, benzodiazepines, SSRIs).  Skyrocketing incidence.

### Presentation
 - Irritability, hypertonia, tremors, poor sleep, poor feeding, vomiting, diarrhea, autonomic dysfunction (sweating, sneezing, tachypnea,fever), weight loss.  Sx diminished in preterm infants 2/2 developmental immaturity of CNS.
- Timing of withdrawal depends on half life: Heroin - <24 hours, Methadone or Buprenorphine: 24-72 hours.

### Management

**First line: Non-pharmacologic**

- Parent rooming in, skin-to-skin, decreased stimulation, clustered care. BMC: Give mother NAS info packet on admission.

- Consoling maneuvers: gentle hold (arms to midline), hand-to-mouth, voice of caregiver (especially parent), holding, swaddling, pacifier, feeding, skin-to-skin

- Breastfeeding for eligible mothers on methadone or buprenorphine **(No relapses in the past 4 weeks, adequate prenatal care, treatment program)**

- **24kcal/oz formula** if not breastfeeding

- **Withdrawal (inability to eat/sleep/console, autonomic sx): Pharmacologic** (at BWH, transfer to NICU, at BMC, follow NAS protocol available on intraweb)

- First-line opioid replacement therapy: methadone, morphine

**Second line therapy: Clonidine, phenobarbital**

- 60-70% of infants exposed to opioids will need therapy, 40-50% if using ESC scoring. Increased risk with methadone and polypharmacy.

- Monitor for at least 5-7 days for infants exposed to methadone or buprenorphine

## Newborn ID
### Early Onset Sepsis

#### Pathophysiology
GBS >> GNRs (especially E. coli, also Klebsiella), some Gram + (Listeria, enterococci, Group D Strep).  Risk of GBS sepsis is 40x higher with heavy maternal colonization.

#### Sepsis RFs
Preterm labor (<37w), maternal intrapartum fever > 100.4F or inadequately treated GBS, PROM (>18h), infant w/ tachycardia/tachypnea/respiratory distress/temp instability

#### Treatment
- **BMC and BWH Algorithm**: Use [Kaiser Neonatal Sepsis calculator](https://neonatalsepsiscalculator.kaiserpermanente.org/) to guide necessity of evaluation (full vs. limited) and/or for antibiotics
- **Empiric abx**: Ampicillin + Gentamicin x 48 hrs.  Substitute cefotaxime/cefepime if suspect meningitis

### Hepatitis B
- Up to 90% of infants infected perinatally or in the first year of life will develop chronic HBV infection
- OK for HepB+ moms to breastfeed

| **Maternal HBsAg** | **BW>2000g**                                                                                                                                             | **BW<2000g**                                                                                                 |
|--------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| **Positive**       | Vaccine + HBIG within 12h (concurrently, different anatomic sites)                                                                                       | Vaccine + HBIG within 12h (concurrently, different anatomic sites)                                           |
| **Unknown**        | - Test mother - HepB vaccine in first 12h - HBIG ASAP if mom positive                                                                                    | - Test mother - HepB vaccine in first 12h - HBIG ASAP if mom positive or if results not available within 12h |
| **Negative**       | - HepB vaccine at birth, within 24 hrs * if parents refuse, discuss again during nursery stay. If still refuses, at BMC must sign informed refusal form. | Delay 1st dose of HepB vaccine until 1 mo of age or hospital discharge, whichever is first                   |

### HIV

#### Management
Consult ID. Get maternal history, lab reports: If mom on ARV and infant low risk for acquiring HIV, testing on infant performed at 14 days, 21 days, 1-2 months, and 4-6 months.  If mother not on ARVs or mom diagnosed during pregnancy, also test infant at birth.

#### Treatment
**Post-exposure prophylaxis ASAP** (within 6 hours of delivery) with **zidovudine** (dosage based on GA at birth and weight) + **nevirapine if mother not on ARVs**

### HSV

#### Pathophysiology
HSV acquired intrauterine (rare), **perinatal** (85% of infections; ↑ risk: **PROM**, fetal scalp monitor/forceps, vaginal delivery, primary infxn in mother -- but **majority of infants w/ HSV born to mothers without known hx of HSV**)

#### Presentation
**Fever or other nonspecific signs of sepsis, coalescing vesicles on erythematous base**, seizures/focality on neuro exam, hepatomegaly, ascites

#### Workup
 - **Asymptomatic**: Swab neonate from cleanest spot to least clean (same swab): conjunctivae, mouth, nasopharynx, rectum @ 24HOL for PCR and culture
 - **Symptomatic**: LP: CSF lymphocyte pleocytosis/elevated protein, consider **EEG, PCR and culture of unroofed vesicle**

#### Treatment
IV Acyclovir 60 mg/kg per day divided q8h (initiate w/ any clinical suspicion; no need to start in asymptomatic infants)  Duration depends on severity.  Monitor renal function and ANC 2x/week.
