# scrapes that shouldn't be deleted


| Formula Name                      | Formula                                                                                                                               | Clinical Use                                                                                                                                                                                 |
|-----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Modified Bedside Schwartz**         | $eGFR=0.413 \times  \frac{height_{(cm)}}{SCr}$                                                                                        | Used ages 1-18 to estimate GFR.                                                                                                                                                              |
| **Insensible Fluid Loss**             | $IFL_{(mL/day)}=300mL/m^{2}/day$ <br><br>$BSA_{(m^{2})}=\sqrt{\frac{ht_{(cm)}\times wt_{(kg)}}{3600}}$                                       | Use for patients when replacing insensible fluid plus urine/stool losses.                                                                                                                    |
| **Total Body Water**                  | $TBW_{males}=wt_{(kg)}\times 0.6$  <br><br> $TBW_{females}=wt_{(kg)}\times 0.5$                                                                | Use to calculate total body water.                                                                                                                                                           |
| **Free Water Deficit**                | $FWD_{(L)}=\left ( \frac{Current\: Na^{+}}{Desired\: Na^{+}} -1\right )\times TBW$                                                    | Calculate **water** to be replaced in **hypernatremic** dehydration.                                                                                                                               |
| **Sodium Deficit**                    | $Na^{+} Deficit_{(mEq)}=(140-Na_{actual}^{+})\times TBW$                                                                              | Calculate **Na<sup>+</sup>** to be replaced in **hyponatremic** dehydration.                                                                                                                                         |
| **Fractional Excretion Sodium**       | $FENa=\frac{\left ( Urine\: Na^{^{+}}\times Plasma\: Cr \right )}{\left ( Plasma\: Na^{+}\times Urine\: Cr \right )}$                 | Use in oliguric **AKI** to determine **prerenal** (<1%, sodium-avid) vs. **intrinsic renal** (&gt; 2%, tubular dysfunction) etiology).                                                                                                                |
| **Fractional Excretion of Urea**      | $FEUrea=\frac{\left ( Urine\: Urea\: Nitrogen\times Plasma\:Cr \right )}{\left ( Plasma\: Urea\: Nitrogen\times Urine\: Cr \right )}$ | Use in **AKI** if patient has recently been given **diuretics** (would alter Na<sup>+</sup> excretion and therefore FENa), acute GN, or CKD; **prerenal** <35%, **intrinsic renal** &gt; 50%.                                                      |
| **Urine Protein/Cr Ratio**            | $UPCR= \frac{Urine\: Protein\: Spot}{Urine\: Cr\: Spot}$                                                                              | Normal <0.2.<br>  > 3.5 indicates nephrotic-range proteinuria.                                                                                                                                   |
| **Transtubular Potassium Gradient**   | $TTKG= \left ( \frac{Urine\: K^{+}}{Plasma\: K^{+}} \right )/{\left ( \frac{Urine\: Osm}{Plasma\: Osm} \right )}$                     | Normal = 8-9.<br>  Can only use when urine osm > plasma osm and urine Na<sup>+</sup> > 25 mmol/L.<br><br> TTKG &lt; 7 +  **hyperkalemia**  → aldo deficiency/resistance  TTKG > 3 +  **hypokalemia**  → aldo ↑ vs renal K<sup>+</sup> loss |
| **Tubular Reabsorption of Phosphate** | $TRP_{\%}=\frac{1-\left ( Urine\: Phosphate \times Plasma\: Cr \right )}{\left ( Plasma\: Cr\times Urine\: Cr \right )}\times 100$    | Normal 80-98%.<br>  ↓ TRP can be seen in conditions with prox tubular dysfunction, such as Fanconi syndrome/Type 2 RTA                                                                               |
| **Urine Calcium/Cr Ratio**            | $UCaCR=\frac{Urine\: Ca^{2+}Spot}{Urine\: Cr\: Spot}$                                                                                 | Normal:<ul><li>0 - 6 months old: ≤ 0.8</li><li>7 - 11 months old: ≤ 0.6</li><li>≥ 1 year old: ≤ 0.2</li></ul> Use to assess for hypercalciuria in patients with hematuria, stones, and/or hypercalcemia.                     |
| **Corrected Calcium**                 | $CorrCa^{2+}=\left ( 4-measured\:albumin \right )\times 0.8+measured\: Ca^{2+}$                                                       | Use to calculate calcium levels in low albumin states.<br><br>  Albumin = negatively charged, and therefore carries calcium.                                                                         |
| **Calculated Serum Osmolality**       | $CalcOsm=\left [ 2\times \left ( Na^{+}+K^{+} \right ) \right ]+\left ( \frac{Glucose}{18} \right )+\left (\frac{BUN}{2.8} \right )$  | Use to calculate serum osmolality.                                                                                                                                                           |
| **Osmolar Gap**                       | $OG=Measured\: SOsm - Calculated\: SOsm$                                                                                              | Osmolar gap > 10 can be caused by toxic alcohols (ethanol, methanol, ethylene glycol, isopropyl alcohol), mannitol, and lorazepam infusions (which contain propylene glycol).                 |



  


# common chemo old table

| Class   - Drugs                                                                                              | Mechanism                                                                                      | Used in                               | Pharma/Metabolism/Excretion                                               | Short-term side effects                                                                                     | Long-term side effects                        | Notes                                                                                                                                    |   |
|--------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|---------------------------------------|---------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|-----------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|---|
| **Alkylating agents** Cyclophosphamide Ifosfamide Melphalan Busulfan Procarbazine Dacarbazine Temozolomide   |        Attaches an alkyl group to guanine in DNA; prevents replication and causes damage       | NBL    Sarcoma   WT   BTs  Lymphoma   | Antagonized by MGMT enzymes; cyclophos via urine, ifos via liver          | N/V/D Mucositis Myelosuppression Hemorrhagic cystitis SIADH IFOS-encephalopathy                             | Secondary malignancy Infertility (high doses) | Co treat w/ Mesna and hyper-hydration for cystitis  IFOS-encephalopathy - methylene blue  Biomarker: MGMT promoter methylation (gliomas) |   |
| **Platinum Analogues** Cisplatin Carboplatin Oxaliplatin                                                     | "Alkylating-like" (no alkyl group); crosslinks w/ DNA, prevents replication and causes damage  | Sarcomas  WT  BTs  GCTs  Testicular   | Urine excretion                                                           | N/V/D Nephrotoxicity Electrolyte wasting (Mag, K)                                                           | Secondary neuropathy Ototoxicity              | Hyperhydration for renal protection                                                                                                      |   |
| **Anti-folate agents** Methotrexate Pemetrexed                                                               | Analog of folic acid, impairs DHFR, thus impairs DNA synthesis                                 | ALL   Lymphoma                        | Hepatic metabolism, but urinary excretion. Elimination is person-specific | Myelosuppression Mucositis Transaminitis Kidney failure Encephalopathy                                      | -                                             | Hyperhydration Urine alkalinization Monitor serum levels Leucovorin  Glucarpidase if unable to clear MTX                                 |   |
| **Anti-metabolites** 6-Mercaptopurine Cytarabine (Ara-C)                                                     | Nucleoside analogue, incorporated into DNA and interrupts replication                          | Leukemia Lymphoma  IT for CNS disease | Kidney (6MP)  Liver (cytarabine)                                          | Myelosuppression N/V/D Mucositis Bowel necrosis Fevers (AraC) Neurotoxicity Infections (esp strep viridans) | -                                             | TPMT genotype (6MP) to guide dosing                                                                                                      |   |
| **Topoisomerase inhibitors** *Topo I inhibitors* Topotecan Irinotecan  *Topo II inhibitors* Etoposide (VP16) | Inhibits Topo I/II during S phase, preventing DNA replication                                  | Solid tumors                          | Liver (etoposide)  Urine (topotecan)                                      | Metallic food taste Myelosuppression Hypotension Diarrhea (irinotecan)                                      | Secondary malignancy                          | Irinotecan-induced diarrhea Prophylaxis: Cefixime Acute onset: atropine >8h: loperamide  UGT1A1 genotype (irinotecan)                    |   |
| **Anthracyclines** Doxorubicin Daunorubicin Idarubicin Mitoxantrone                                          | Antibiotic from Streptomyces bacteria; Intercalates between DNA/RNA hybrids in replication.    | Leukemia Sarcomas Lymphoma            | Liver                                                                     | Myelosuppression Mucositis Skin reactions (hand-foot syndrome)                                              | Heart failure (cumulative dose-dependent)     | Dexrazoxane may be used in limited cases for patients at highest risk of developing cardiotoxicity                                       |   |
| **Asparaginase** PEG- Non-PEG (Erwinia)-                                                                     | Bacterial enzyme, converts asparagine to aspartic acid and ammonia. Inhibits protein synthesis | ALL    AML                            | PEG half life 5-7 days, Non-PEG half life <24 hours                       | Anaphylaxis Coagulopathy/Thrombosis Hyperammonemia Encephalopathy Hemorrhagic pancreatitis Transaminitis    | -                                             |                                                                                                                                          |   |
| **Vinca alkaloids** Vincristine Vinblastine Vinorelbine                                                      | Inhibits mitotic M phase by preventing microtubule function                                    | ALL Lymphoma Sarcoma CNS NBL WT       | Liver                                                                     | Neurotoxicity Peripheral neuropathy SIADH Constipation Seizures Hypotension                                 | -                                             | Bowel regimen                                                                                                                            |   |
